version: "3.2"
services:
  web:
    image: "registry.thinklabs.com.vn:5000/pktunganhweb:latest"
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.environment==development]
      restart_policy:
        condition: any
    environment:
      PORT: 80
      NODE_ENV: "production"
      SERVICE_80_NAME: "pktunganhweb"
      SERVICE_NAME: "pktunganhweb"
      SERVICE_TAGS: "pktunganhweb"
    ports:
      - target: 80
        published: 8023
        mode: host
