version: "3.6"
services:
  admin:
    image: "dauphucdfcadmin:latest"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      PORT: 80
      NODE_ENV: "production"
    ports:
      - "8100:80"