// khai báo các name actions
export const FETCH_DANHMUCGIA = "FETCH_DANHMUCGIA";
export const FETCH_DANHMUCGIA_SUCCESS = "FETCH_DANHMUCGIA_SUCCESS";
export const FETCH_DANHMUCGIA_ERROR = "FETCH_DANHMUCGIA_ERROR";

