// khai báo các name actions
export const FETCH_KHOA = "FETCH_KHOA";
export const FETCH_KHOA_SUCCESS = "FETCH_KHOA_SUCCESS";
export const FETCH_KHOA_ERROR = "FETCH_KHOA_ERROR";

export const FETCH_LOAIKHOA = "FETCH_LOAIKHOA";
export const FETCH_LOAIKHOA_SUCCESS = "FETCH_LOAIKHOA_SUCCESS";
export const FETCH_LOAIKHOA_ERROR = "FETCH_LOAIKHOA_ERROR";

export const FETCH_SPHONG = "FETCH_SPHONG";
export const FETCH_SPHONG_SUCCESS = "FETCH_SPHONG_SUCCESS";
export const FETCH_SPHONG_ERROR = "FETCH_SPHONG_ERROR";

