// khai báo các name actions
export const FETCH_LOAIDV = "FETCH_LOAIDV";
export const FETCH_LOAIDV_SUCCESS = "FETCH_LOAIDV_SUCCESS";
export const FETCH_LOAIDV_ERROR = "FETCH_LOAIDV_ERROR";

export const FETCH_HOATCHAT = "FETCH_HOATCHAT";
export const FETCH_HOATCHAT_SUCCESS = "FETCH_HOATCHAT_SUCCESS";
export const FETCH_HOATCHAT_ERROR = "FETCH_HOATCHAT_ERROR";

export const FETCH_NHOMTHUOC = "FETCH_NHOMTHUOC";
export const FETCH_NHOMTHUOC_SUCCESS = "FETCH_NHOMTHUOC_SUCCESS";
export const FETCH_NHOMTHUOC_ERROR = "FETCH_NHOMTHUOC_ERROR";

export const FETCH_DVT = "FETCH_DVT";
export const FETCH_DVT_SUCCESS = "FETCH_DVT_SUCCESS";
export const FETCH_DVT_ERROR = "FETCH_DVT_ERROR";

export const FETCH_DV = "FETCH_DV";
export const FETCH_DV_SUCCESS = "FETCH_DV_SUCCESS";
export const FETCH_DV_ERROR = "FETCH_DV_ERROR";

export const FETCH_DUONGDUNG = "FETCH_DUONGDUNG";
export const FETCH_DUONGDUNG_SUCCESS = "FETCH_DUONGDUNG_SUCCESS";
export const FETCH_DUONGDUNG_ERROR = "FETCH_DUONGDUNG_ERROR";

