// khai báo các name actions
export const FETCH_TINHTHANH = "FETCH_TINHTHANH";
export const FETCH_TINHTHANH_SUCCESS = "FETCH_TINHTHANH_SUCCESS";
export const FETCH_TINHTHANH_ERROR = "FETCH_TINHTHANH_ERROR";

export const FETCH_QUANHUYEN = "FETCH_QUANHUYEN";
export const FETCH_QUANHUYEN_SUCCESS = "FETCH_QUANHUYEN_SUCCESS";
export const FETCH_QUANHUYEN_ERROR = "FETCH_QUANHUYEN_ERROR";

export const FETCH_PHUONGXA = "FETCH_PHUONGXA";
export const FETCH_PHUONGXA_SUCCESS = "FETCH_PHUONGXA_SUCCESS";
export const FETCH_PHUONGXA_ERROR = "FETCH_PHUONGXA_ERROR";
