// khai báo các name actions
export const FETCH_PHAI = "FETCH_PHAI";
export const FETCH_PHAI_SUCCESS = "FETCH_PHAI_SUCCESS";
export const FETCH_PHAI_ERROR = "FETCH_PHAI_ERROR";

export const FETCH_DANTOC = "FETCH_DANTOC";
export const FETCH_DANTOC_SUCCESS = "FETCH_DANTOC_SUCCESS";
export const FETCH_DANTOC_ERROR = "FETCH_DANTOC_ERROR";

export const FETCH_QUOCTICH = "FETCH_QUOCTICH";
export const FETCH_QUOCTICH_SUCCESS = "FETCH_QUOCTICH_SUCCESS";
export const FETCH_QUOCTICH_ERROR = "FETCH_QUOCTICH_ERROR";

export const FETCH_NGHENGHIEP = "FETCH_NGHENGHIEP";
export const FETCH_NGHENGHIEP_SUCCESS = "FETCH_NGHENGHIEP_SUCCESS";
export const FETCH_NGHENGHIEP_ERROR = "FETCH_NGHENGHIEP_ERROR";

export const FETCH_NHANVIEN = "FETCH_NHANVIEN";
export const FETCH_NHANVIEN_SUCCESS = "FETCH_NHANVIEN_SUCCESS";
export const FETCH_NHANVIEN_ERROR = "FETCH_NHANVIEN_ERROR";